### ISSUE TITLE
rcap.AuthHeader should have yaml tags

### ISSUE THREAD

**Issue by cohix** [suborbital/reactr#122]
Since there are no yaml tags on rcap.AuthHeader, they don't work well in the Directive (causing us to create a duplicate type for it)... so we should add those tags to the struct in this package so we don't need the duplicate.

**Comment by krishnaindani** [comment]
Hey, I would like to check if I can contribute to this issue.

**Comment by cohix** [comment]
@krishnaindani yes, by all means! If you take this one on, there's also a follow-up in the atmo repo as well.

**Comment by krishnaindani** [comment]
do you have an idea on follow-up with this issue? Also with his issue I only see adding YAML tags on the https://github.com/suborbital/reactr/blob/503859d8a618250e0abc3f27b4010d829b51b6b6/rcap/authentication.go#L14 struct, do I need to address something else, could you please elaborate?

**Comment by cohix** [comment]
> do you have an idea on follow-up with this issue? Also with his issue I only see adding YAML tags on the https://github.com/suborbital/reactr/blob/503859d8a618250e0abc3f27b4010d829b51b6b6/rcap/authentication.go#L14 struct, do I need to address something else, could you please elaborate?

Once the yaml tags are added here, the `directive` package in the [atmo](https://github.com/suborbital/atmo) repo should be updated to use this struct instead of the copy in that repo. It would require tagging a new release of Reactr and updating the dependency in Atmo, so it should be a follow-up issue.

**Comment by cohix** [comment]
@krishnaindani I was able to handle this issue in https://github.com/suborbital/reactr/pull/123

Would love to see you contribute, though! Please reach out if you're interested: https://chat.suborbital.dev
