### ISSUE TITLE
Performance benchmarks for rwasm ( its dependency on wasmer-go)

### ISSUE THREAD

**Issue by venugopv** [suborbital/reactr#57]
Hi,  We are evaluating rwasm/reactr to use in one of our WebAssembly project. As rwasm uses wasmer-go as its wasm engine and its indirect dependency on CGO, we are interested to know its performance. Generally CGO may come with some performance penalties:  https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/.  It would be great if you share some performance benchmarks.

**Comment by cohix** [comment]
@venugopv Sure, I'd be happy to provide some benchmarks. What kinds of things are you looking to see?

**Comment by venugopv** [comment]
Hi @cohix , Thanks for quick response. Basically our use case involves many interactions from WASM module (Guest side) to wasm embedder (Host side) to access Host functions (like HTTP functionality. Suborbital::http is exact match to us). Coupling the fact that we would be running 100 of wasm instances in parallel.

So some thing like this: We would be running 100 of instances of similar to Fetch sample (https://github.com/suborbital/reactr/blob/main/rwasm/testdata/fetch/src/lib.rs). From my limited research on CGO, I am under the impression, there would be significant performance penalty. I am interested to know what do you see when you run some thing similar to above (i.e  running 100 of instances of similar to Fetch sample ).

**Comment by cohix** [comment]
@venugopv thanks for the detail. I will spend some time this week creating something to demo performance for your use-case. In the meantime, please do explore the docs and examples and let me know if there is anything missing that I can add!

**Comment by cohix** [comment]
Alright so I've run some tests locally, and assuming these results are what you're looking for, I'll push the benchmarks to main so you can try it yourself. If this isn't what you're looking for, let me know and I'll do another round.

`BenchmarkRunnableFetch-16    	      10	 120235191 ns/op	  107026 B/op	     257 allocs/op`

That benchmark is just `http::get`'ing the Google homepage. The ns/op translates to 0.120 seconds/op.

When I do 10 invocations of cURL on the same URL, I get a mean request time of 0.116 seconds.

So average of 120ms per request for Reactr and 116ms per request for cURL. Not a perfect comparison for sure, but it's at least a basic look.

@venugopv Let me know if you'd like to see anything else!

**Comment by cohix** [comment]
@venugopv Any update here?

**Comment by venugopv** [comment]
Hi @cohix , Thanks very much for your inputs.  We have further evaluated on usage of CGO and golang particular, we have decided to  embed Webassembly in Rust as it suits more to our use case.
